GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/2

###
POST http://localhost:3000/ads
Content-Type: application/json

{
    "title": "My first real ad!",
    "description": "lorem ipsum blablablabla",
    "owner": "anon@gmail.com",
    "price": 42,
    "picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Paris",
    "createdAt": "2024-10-05T10:14:15.922Z",
    "id_category":3
}

###
DELETE http://localhost:3000/ads/4

###
PUT http://localhost:3000/ads/4
Content-Type: application/json

{
    "name":"blu"
}

###
PATCH http://localhost:3000/ads/4
Content-Type: application/json

{
    "title":"blu"
}

